theme: jekyll-theme-minimal

title: Aadarsha Dhakal
description: [A short description of ys purpose]
logo: IMG_20191123_124129.jpg
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
