theme: jekyll-theme-minimal

title: Aadarsha Dhakal
description: [Self-motivated Mobile App Developer, adept at building mobile apps based on customer preferences using latest technology including but not limited to Dart Programming Language and Flutter UI Toolkit. I have decent knowledge of other programming languages : C, C++, and Python. Having worked at different software companies till now, I can reckon I have developed good communication and in-depth problem solving skills. Leaning on work ethics, I not only look for me, but also for the benefit of the company and the clients themselves. I am dedicated, hard-working and enthusiastic young who always craves learning more about new technology everyday.]
logo: IMG_20191123_124129.jpg
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
