theme: jekyll-theme-minimal

title: Aadarsha Dhakal
description: [A short description of ys purpose]
logo: IMG_20191123_124129.jpg
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
